<?php

function enorm_facturen_node_view_alter(&$build) {
    if($build['#bundle'] === 'content_type_invoice') {
        $info = enorm_facturen_get_invoice_info($build['field_invoice_invoice_id'][0]['#markup']);
        $build['field_invoice_status'][0]['#markup'] = ucfirst($info['data']['status']);
        if($info['data']['invoice_number'] != NULL) {
            $build['field_invoice_number'][0]['#markup'] = $info['data']['invoice_number'];
        }
        else {
            $build['field_invoice_number'][0]['#markup'] = "Invoice is still a draft, no number is available.";
        }
        $date = explode("-", $info['data']['invoice_date']);
        $build['field_invoice_date'][0]['#markup'] = $date[2] . "/" .  $date[1] . "/" . $date[0];
        if(empty($info['data']['due_on'])) {
            $build['field_invoice_due_on'][0]['#markup'] = "Invoice is still a draft, no due date is available.";
        }
        else {
            $date_due = explode("-", $info['data']['due_on']);
            $build['field_invoice_due_on'][0]['#markup'] = $date_due[2] . "/" .  $date_due[1] . "/" . $date_due[0];
        }
        if($info['data']['paid'] === FALSE) {
            $build['field_invoice_paid'][0]['#markup'] = "No";
        }
        else {
            $build['field_invoice_paid'][0]['#markup'] = "Yes";
        }
        $build['field_invoice_total'][0]['#markup'] = $info['data']['total']['payable']['amount'] . " " . $info['data']['total']['payable']['currency'];

    }
}

function enorm_facturen_get_invoice_info($invoice_id) {
    $operation = "invoices.info";
    $postfields = "{
      \"id\": \"" . $invoice_id . "\"
    }";
    return enorm_teamleader_call($operation, $postfields);
}
















