<?php

function enorm_facturen_node_view_alter(&$build) {
    if($build['#bundle'] === 'content_type_invoice') {
        $info = enorm_facturen_get_invoice_info($build['field_invoice_invoice_id'][0]['#markup']);
        $build['field_invoice_status'][0]['#markup'] = ucfirst($info['data']['status']);
        if($info['data']['invoice_number'] != NULL) {
            $build['field_invoice_number'][0]['#markup'] = $info['data']['invoice_number'];
        }
        else {
            $build['field_invoice_number'][0]['#markup'] = "Invoice is still a draft, no number is available.";
        }
        $build['field_invoice_date'][0]['#markup'] = $info['data']['invoice_date'];
        if($info['data']['due_on'] != NULL) {
            $build['field_invoice_due_on'][0]['#markup'] = $info['data']['due_on'];
        }
        else {
            $build['field_invoice_number'][0]['#markup'] = "Invoice is still a draft, no due date is available.";
        }
        if($info['data']['paid'] === FALSE) {
            $build['field_invoice_paid'][0]['#markup'] = "No";
        }
        else {
            $build['field_invoice_paid'][0]['#markup'] = "Yes";
        }
        $build['field_invoice_total'][0]['#markup'] = $info['data']['total']['due']['amount'] . $info['data']['total']['due']['currency'];

    }
}

function enorm_facturen_get_invoice_info($invoice_id) {
    $operation = "invoices.info";
    $postfields = "{
      \"id\": \"" . $invoice_id . "\"
    }";

    return enorm_teamleader_call($operation, $postfields);
}
















