<?php

function enorm_milestones_node_view_alter(&$build)
{
    if ($build['#bundle'] === 'content_type_project') {
        $project_id = $build['field_project_teamleader_id'][0]['#markup'];
        $milestones = enorm_milestones_get_info($project_id);
        $milestone_amount = count($milestones['data']);
        if (!empty($milestones)) {
            $build['field_project_milestones'][0]['#markup'] = '';
            for ($x = 0; $x < $milestone_amount; $x++) {
                $due_date = explode("-", $milestones['data'][$x]['due_on']);
                $build['field_project_milestones'][0]['#markup'] = $build['field_project_milestones'][0]['#markup'] . $milestones['data'][$x]['name'] . ', status: ' . $milestones['data'][$x]['status'] . '. Due on: ' .$due_date[2] . "/" .  $due_date[1] . "/" . $due_date[0] . '<br><br>';
            }
        }
    }
}

function enorm_milestones_get_info($id)
{
    $operation = "milestones.list";
    $postfields = "{
      \"filter\": {
        \"project_id\": \"" . $id . "\"
      },
      \"page\": {
        \"size\": 100,
        \"number\": 1
      },
      \"sort\": [
        {
          \"field\": \"due_on\",
          \"order\": \"desc\"
        }
      ]
    }";
    return enorm_teamleader_call($operation, $postfields);
}