<?php

function enorm_milestones_node_view_alter(&$build)
{
    if ($build['#bundle'] === 'content_type_project') {
        $project_id = $build['field_project_teamleader_id'][0]['#markup'];
        $milestones = enorm_milestones_get_info($project_id);
        $milestone_amount = count($milestones['data']);
        $active = 0;
        $closed = 0;
        $timetracking = 0;
        $build['field_project_milestones'][0]['#markup'] = '';
        for ($x = 0; $x < $milestone_amount; $x++) {
            if($milestones['data'][$x]['status'] == 'closed') {
                $closed++;
            }
            elseif($milestones['data'][$x]['status'] == 'open'){
                $active++;
            }
            $due_date = explode("-", $milestones['data'][$x]['due_on']);
            $timetracking += enorm_timetracking_get_timetracking_list($milestones['data'][$x]['id']);
            $build['field_project_milestones'][0]['#markup'] = $build['field_project_milestones'][0]['#markup'] . $milestones['data'][$x]['name'] . ', status: ' . $milestones['data'][$x]['status'] . '. Due on: ' . $due_date[2] . "/" . $due_date[1] . "/" . $due_date[0] . '<br><br>';
        }
        $timetracking = round($timetracking / 60 / 60);
        $build['field_project_hours_spent'][0]['#markup'] = $timetracking . '<br><p>hours tracked to project.</p>';
        $total = $closed + $active;
        $percentage = round($closed / $total * 100) . "%";
        $build['field_project_percentage'][0]['#markup'] = $percentage;
    }
}

function enorm_milestones_get_info($id)
{
    $operation = "milestones.list";
    $postfields = "{
      \"filter\": {
        \"project_id\": \"" . $id . "\"
      },
      \"page\": {
        \"size\": 100,
        \"number\": 1
      },
      \"sort\": [
        {
          \"field\": \"due_on\",
          \"order\": \"desc\"
        }
      ]
    }";
    return enorm_teamleader_call($operation, $postfields);
}